### ISSUE TITLE
phar-build

### ISSUE THREAD

**Issue by chervox** [koto/phar-util#4]
Hi:
   I came accross another issue using this tool in the same block of code:
    // buildFromIterator unfortunately sucks and skips nested directories (?)
    foreach ($iterator as $file) {
                echo "adding " . $file . PHP_EOL;
                if ($file->isFile()) {
                    $phar->addFile($file, str_replace($options['src'], '', $file));
                }
                if ($file->isDir() && !$iterator->isDot()) {
                    // this also doesn't work :(
                    $phar->addEmptyDir(str_replace($options['src'], '', $file));
                }
        }
    }
the thing is that if you use this code against a dir structure like a/b/a/c.php then the str_replace will replace both "a" giving back something like /b//c.php and the build will fail... 
so my propose about this is using the ltrim function that ensures the strip just from the beginning of the string,
also a suggest about this piece of code is that the check on the !$iterator->isDot() is made in the entire block of code so we don't get the adding a/b/c/. and a/b/c/.. and we avoid the entire process on that. 
So the proposed piece of code:
    foreach ($iterator as $file) {
        if (!$iterator->isDot()){
                echo "adding " . $file . PHP_EOL;
                if ($file->isFile()) {
                    //$phar->addFile($file, str_replace($options['src'], '', $file));
                    $phar->addFile($file, ltrim($file,$options['src']));
                }
                if ($file->isDir() ) {
                    // this also doesn't work :(
                    // $phar->addEmptyDir(str_replace($options['src'], '', $file));
                    $phar->addEmptyDir(ltrim($file,$options['src']));
                }
        }
    }

again thanks for this job, :D

**Comment by koto** [comment]
Fixed, will be in v0.5.5
